import random
import operator

# program generated by Cursor
def generate_expression():
    """Generate a random arithmetic expression"""
    ops = [('+', operator.add), ('-', operator.sub), 
           ('*', operator.mul), ('/', operator.truediv)]
    
    # Generate two random numbers between 1-100
    num1 = random.randint(1, 100)
    num2 = random.randint(1, 100)
    
    # Select random operator
    op_symbol, op_func = random.choice(ops)
    
    # Skip division by zero and keep results reasonable
    if op_symbol == '/' and num2 == 0:
        num2 = random.randint(1, 100)
        
    expression = f"{num1} {op_symbol} {num2}"
    try:
        result = op_func(num1, num2)
        # Round result to 4 decimal places
        result = round(result, 4)
        return expression, str(result)
    except:
        # In case of division errors etc, try again
        return generate_expression()

def main():
    num_examples = 1000
    
    with open("arithmetic_input.txt", "w") as f_in, \
         open("arithmetic_output.txt", "w") as f_out:
        
        for _ in range(num_examples):
            expr, res = generate_expression()
            f_in.write(expr + "\n")
            f_out.write(res + "\n")

if __name__ == "__main__":
    main()
